### ISSUE TITLE
err: TypeError: Cannot read property 'projects' of undefined

### ISSUE THREAD

**Issue by pan93412** [xaoxuu/hexo-theme-stellar#15]
## Description

Stellar 從 175dff3f7615d451cdbd0bd3e0c838de12d982c4 升級到最新提交 (main, 2957f109df93eeda3a663e5ead041972f531c9ba) 後，`npm run server` 會在 Stellar 處理階段報出 `TypeError: Cannot read property 'projects' of undefined` 錯誤。

## Environment

- Hexo 版本：`v5.4.0`
- Stellar 版本：
  - 目前： 2957f109df93eeda3a663e5ead041972f531c9ba
  - 先前： 175dff3f7615d451cdbd0bd3e0c838de12d982c4
- 作業系統：macOS Monterey (12.0 Beta, 21A5268h)
- Node.js 版本：v16.4.1 (ARM64)
- 復現 Repo：https://github.com/pan93412/pan.blog/tree/broke/projects-undefined

## Checklist

- [x] 我已根據官網說明正確設定（及更新）所有設定檔
- [x] 我在 blog 根目錄執行過一次 `npm i`
- [x] 我在 stellar 主題目錄執行過一次 `npm i`
- [x] 刪除所有 `node_modules` 並重新執行上述兩步驟後問題依舊
- [x] 先前（使用 GitHub CI 時）沒有問題   

## Logs

```
➜  pan.blog git:(source) rm -rf node_modules                          
➜  pan.blog git:(source) npm i                                        
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated cryptiles@0.2.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated boom@0.4.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@0.2.4: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated hoek@0.9.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated request@2.51.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hawk@1.1.1: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.

added 589 packages, and audited 590 packages in 3s

30 packages are looking for funding
  run `npm fund` for details

25 vulnerabilities (2 low, 14 moderate, 9 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

```
➜  pan.blog git:(source) cd themes/stellar/
➜  stellar git:(2957f10) npm i
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

added 40 packages, and audited 41 packages in 1s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  stellar git:(2957f10) ✗ cd ../..
```

```
➜  pan.blog git:(source) npm run server                               

> hexo-site@0.0.0 server
> hexo server

INFO  Validating config
INFO  
=======================================================
  Stellar 1.2.1
  Docs: https://xaoxuu.com/wiki/stellar/
  Repo: https://github.com/xaoxuu/hexo-theme-stellar/
=======================================================
INFO  Start processing
FATAL {
  err: TypeError: Cannot read property 'projects' of undefined
      at module.exports (/Users/pan93412/Projects/pan.blog/themes/stellar/scripts/events/lib/doc_tree.js:29:42)
      at Hexo.<anonymous> (/Users/pan93412/Projects/pan.blog/themes/stellar/scripts/events/index.js:8:28)
      at Hexo.emit (node:events:406:35)
      at Hexo._generate (/Users/pan93412/Projects/pan.blog/node_modules/hexo/lib/hexo/index.js:452:10)
      at /Users/pan93412/Projects/pan.blog/node_modules/hexo/lib/hexo/index.js:356:19
      at tryCatcher (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/pan93412/Projects/pan.blog/node_modules/bluebird/js/release/promise.js:729:18)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

**Comment by xaoxuu** [comment]
感謝提供了詳細的信息，我找到了問題的原因，今天晚上會發布修復版本。
