### ISSUE TITLE
hexo g的过程中报错

### ISSUE THREAD

**Issue by v2ish1yan** [xaoxuu/hexo-theme-stellar#297]
在执行命令hexo g的过程中报错
```
INFO  Start processing
FATAL {
  err: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  
    assert(cache[index])
  
      at /home/blog/node_modules/hexo/lib/hexo/post.js:25:3
      at String.replace (<anonymous>)
      at PostRenderCache.restoreCodeBlocks (/home/blog/node_modules/hexo/lib/hexo/post.js:43:16)
      at /home/blog/node_modules/hexo/lib/hexo/post.js:301:31
      at tryCatcher (/home/blog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/blog/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/blog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/blog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/blog/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/blog/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/home/blog/node_modules/bluebird/js/release/promise.js:489:14)
      at Promise._settlePromiseFromHandler (/home/blog/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/home/blog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/blog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/blog/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/blog/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._settlePromise (/home/blog/node_modules/bluebird/js/release/promise.js:617:21)
      at Promise._settlePromise0 (/home/blog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/blog/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/blog/node_modules/bluebird/js/release/promise.js:673:18)
      at /home/blog/node_modules/bluebird/js/release/nodeback.js:42:21
      at /home/blog/node_modules/nunjucks/src/environment.js:41:5 {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: null,
    expected: true,
    operator: '=='
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```
使用其他主题的使用不会这样，请问怎么解决呀

**Comment by v2ish1yan** [comment]
我知道为什么了，这个是因为这个主题不支持_post内的多级目录导致的，把里面的子目录删了就可以了

**Comment by xaoxuu** [comment]
我的文章都是在子目录里放的：
<img width="315" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/4fcf7152-8dd4-4214-844b-cc2d76078607">

**Comment by hack3r0pium** [comment]
为什么我没有子目录也报这个错，求解
