### ISSUE TITLE
不支持_posts内子目录导致报错

### ISSUE THREAD

**Issue by v2ish1yan** [xaoxuu/hexo-theme-stellar#298]
在_posts内使用子目录就会导致报错
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/90122035/0833658f-8991-4df4-b15f-f1be28358025)

```
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(cache[index])

    at /home/blog/hexo/node_modules/hexo/lib/hexo/post.js:43:7
    at String.replace (<anonymous>)
    at PostRenderEscape.restoreCodeBlocks (/home/blog/hexo/node_modules/hexo/lib/hexo/post.js:56:16)
    at /home/blog/hexo/node_modules/hexo/lib/hexo/post.js:430:31
    at tryCatcher (/home/blog/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:489:14)
    at Promise._settlePromiseFromHandler (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._settlePromise (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:617:21)
    at Promise._settlePromise0 (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/blog/hexo/node_modules/bluebird/js/release/promise.js:673:18)
    at /home/blog/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/blog/hexo/node_modules/nunjucks/src/environment.js:28:5
```

**Comment by xaoxuu** [comment]
我的文章都是在子目录里放的：
<img width="315" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/16400144/f8a6f703-8454-4eb1-a6da-0616ce43f252">
