### ISSUE TITLE
一个很怪的报错

### ISSUE THREAD

**Issue by v2ish1yan** [xaoxuu/hexo-theme-stellar#303]
当md文件中，在两个图片中间，有一个代码块，且内容为`))`的时候，执行`hexo g`的时候就会报错
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/90122035/8ce4527c-3a94-4e1d-9f98-c26f7562f46f)

报错代码
```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(cache[index])

    at D:\Blog\node_modules\hexo\lib\hexo\post.js:43:7
    at String.replace (<anonymous>)
    at PostRenderEscape.restoreCodeBlocks (D:\Blog\node_modules\hexo\lib\hexo\post.js:56:16)
    at D:\Blog\node_modules\hexo\lib\hexo\post.js:430:31
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (D:\Blog\node_modules\bluebird\js\release\promise.js:489:14)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:617:21)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:673:18)
    at D:\Blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\Blog\node_modules\nunjucks\src\environment.js:28:5
```
然后把上下的图片删掉一个，或者把))删掉，就不会报错

我的md文件内容的源代码
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/90122035/59bfd2a8-9e51-42d4-8d8d-bbb7663c1fa6)

**Comment by v2ish1yan** [comment]
只要中间的代码块有一个)就会报错
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/90122035/ee1cdca0-6cc8-4499-98ca-d37182bed2d2)

**Comment by xaoxuu** [comment]
可能是解析问题，我也没有办法

**Comment by v2ish1yan** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月7日(周三) 晚上6:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xaoxuu/hexo-theme-stellar] 一个很怪的报错 (Issue #303)




 
可能是解析问题，我也没有办法
