### ISSUE TITLE
Stellar 主题创建专栏出错

### ISSUE THREAD

**Issue by sakurasep** [xaoxuu/hexo-theme-stellar#397]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [ ] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

你好，我在部署专栏的时候遇到了这一个问题
```
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot create property 'id' on string 'Buaservemediaserver.ymlIlocblob�.������
         zerotech.ymlIlocblobA0������
                                     @� @ @ @
                                             E�DSDB  @ @ @'
    at getTopicTree (/Users/sakurasep/文件/Blog/Sakura_Blog/themes/stellar/scripts/events/lib/topic_tree.js:19:14)
    at module.exports (/Users/sakurasep/文件/Blog/Sakura_Blog/themes/stellar/scripts/events/lib/topic_tree.js:39:16)
    at Hexo.<anonymous> (/Users/sakurasep/文件/Blog/Sakura_Blog/themes/stellar/scripts/events/index.js:11:30)
    at Hexo.emit (node:events:525:35)
    at Hexo._generate (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/hexo/lib/hexo/index.js:453:10)
    at /Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/hexo/lib/hexo/index.js:324:19
    at tryCatcher (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._settlePromise (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:617:21)
    at Promise._settlePromise0 (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray.init (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise_array.js:75:18)
    at Promise._settlePromise (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/sakurasep/文件/Blog/Sakura_Blog/node_modules/bluebird/js/release/promise.js:673:18)
```
我下载官方 demo 后，将我的博客中的_data/topic 中的配置文件放入后可以正常创建专栏
我的博客的_data结构如下图
<img width="231" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/70024132/a110a3b5-fda5-4af5-b008-65082a5a549a">
现在的情况是如果我不使用专栏整个博客可以正常部署，使用专栏就会报错

**Comment by sakurasep** [comment]
补充一下 npm的版本好像没问题，但是子模块的53fddd24be63f355a320013eeddac4c701e933e7出现了错误

**Comment by xaoxuu** [comment]
```
Buaservemediaserver.ymlIlocblob�.������
         zerotech.ymlIlocblobA0������
                                     @� @ @ @
                                             E�DSDB  @ @ @
```
这个是啥？乱码了吧

**Comment by sakurasep** [comment]
> ```
> Buaservemediaserver.ymlIlocblob�.������
>          zerotech.ymlIlocblobA0������
>                                      @� @ @ @
>                                              E�DSDB  @ @ @
> ```
> 
> 这个是啥？乱码了吧
> 
> 从 `Buaservemediaserver` 看，应该是有个地方的缩进有问题导致识别出错了，把后面一大串都当做前面某个东西的值了。

我也不太清楚是哪里的缩进出了问题，主题文件我是没有碰过。。我再查一下吧。
我是在 macOS 上部署的博客，这个乱码我看看有啥办法显示。

**Comment by sakurasep** [comment]
我这边怀疑是 macOS 的问题
我刚才做了一个测试，在一个新的文件夹用 hexo init 初始化了一个 hexo，然后用 npm 安装 stellar 博客，这相当于创建了一个全新的环境。
然后我第一次把主题 demo 的 _data/topic 直接拷贝到 source 中，然后部署后发现没有问题，能正常显示专栏
<img width="580" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/70024132/2e5a2ff4-4929-4869-8bb6-faa837cd80e3">
然后我拷贝 demo 中的 aaa.yml 分别改成 bbb.yml ccc.yml 仍然没有出错
第二次是自己创建_data/topic, 然后手动复制 demo 中的文件到 topic中 ，此时就报错了
<img width="868" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/70024132/016bfa31-7e09-4250-ab96-9651364946f6">

**Comment by sakurasep** [comment]
头疼，佬需要我提供什么文件吗

**Comment by xaoxuu** [comment]
检查过md文件吗

**Comment by sakurasep** [comment]
测了一段时间，好像是 macOS 的问题？
我在 windows 上创建了一个同样的环境，无论怎么增加或者改变 topic 内的文件，都可以成功编译
<img width="1008" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/70024132/8601f7b8-0199-45fe-9650-bf46dfc8849e">
macOS 如果要不报错，只有一种方法，就是一个全新的文件夹，只要你创建了 topic，并且成功的编译了此文件一次，后续就不可以删除这个 topic 以及新建文件删除文件了

**Comment by sakurasep** [comment]
应该确定了是 macOS 的问题了，同样的一份代码
### 本地 macOS
<img width="654" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/70024132/cc43dd1a-6b08-4067-8603-bbffeda1e080">

### GitHub Action
<img width="735" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/70024132/f5874e2b-fb2d-4dc9-8523-8d17f6f483c3">

很无语，想不出来哪里的问题

**Comment by L33Z22L11** [comment]
请尝试在此项目停用 npm 的 package-lock 机制，删除 `node_modules/` 文件夹后重新执行 `npm install`。

**Comment by xaoxuu** [comment]
贴一下所有包含mediaserver这个topic的md文件的front-matter

**Comment by sakurasep** [comment]
<img width="996" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/70024132/7747d54c-4d94-4c93-9f1d-827174507252">

**Comment by sakurasep** [comment]
目前还没有任何 md 文件使用这个 topic,我现在相当于是测试，改了好几次文件名都会出错

**Comment by xaoxuu** [comment]
试一下在根目录配置文件 `_config.yml` 中找到 `ignore:` 并修改为：

```yaml
ignore:
  - .DS_Store
  - /**/.DS_Store
```

**Comment by sakurasep** [comment]
> ```yaml
>   - .DS_Store
>   - /**/.DS_Store
> ```

试了之后经过简单测试已经解决，原来是这里的问题。

**Comment by xaoxuu** [comment]
那我在主题里过滤一下这个文件
