### ISSUE TITLE
开启related_posts后打开文章报错

### ISSUE THREAD

**Issue by winsoft666** [xaoxuu/hexo-theme-stellar#435]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

安装hexo-related-popular-posts插件，开启 related_posts后打开文章就报错：
```
related_posts:
    enable: true
    max_count: 5
```

报错内容如下：
```
Unhandled rejection TypeError [ERR_INVALID_ARG_TYPE]: D:\CODE\OOO\hexo-blog\themes\stellar\layout\page.ejs:58
    56| %>
    57|
 >> 58| <%- layoutDiv() %>
    59|

D:\CODE\OOO\hexo-blog\themes\stellar\layout\_partial\main\article\related_posts.ejs:16
    14| }
    15| %>
 >> 16| <%- layoutDiv() %>
    17|

The "path" argument must be of type string. Received null
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:433:7)
    at getElm (D:\CODE\OOO\hexo-blog\node_modules\hexo-related-popular-posts\lib\list-json.js:371:28)
    at module.exports.getList (D:\CODE\OOO\hexo-blog\node_modules\hexo-related-popular-posts\lib\list-json.js:383:23)
    at module.exports (D:\CODE\OOO\hexo-blog\node_modules\hexo-related-popular-posts\lib\helper-json.js:3:19)
    at Object.<anonymous> (D:\CODE\OOO\hexo-blog\node_modules\hexo-related-popular-posts\index.js:177:40)
    at layoutDiv ("D:\\CODE\\OOO\\hexo-blog\\themes\\stellar\\layout\\_partial\\main\\article\\related_posts.ejs":17:13)
    at eval ("D:\\CODE\\OOO\\hexo-blog\\themes\\stellar\\layout\\_partial\\main\\article\\related_posts.ejs":28:17)
    at related_posts (D:\CODE\OOO\hexo-blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\CODE\OOO\hexo-blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\CODE\OOO\hexo-blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\CODE\OOO\hexo-blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at layoutDiv ("D:\\CODE\\OOO\\hexo-blog\\themes\\stellar\\layout\\page.ejs":60:11)
    at eval ("D:\\CODE\\OOO\\hexo-blog\\themes\\stellar\\layout\\page.ejs":69:17)
    at page (D:\CODE\OOO\hexo-blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\CODE\OOO\hexo-blog\node_modules\hexo\lib\theme\view.js:136:50)
```

**Comment by winsoft666** [comment]
启用评论之后，错误就没没有了
