### ISSUE TITLE
waline、giscus评论组件在生产环境一直 loading

### ISSUE THREAD

**Issue by resetsix** [xaoxuu/hexo-theme-stellar#441]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

`giscus`在本地就跑起来，但是部署到 `vercel` 生产环境之后就一直 `loading`；`waline`开发环境和生产环境都是 `loading`。

`waline`的`serverURL`服务确保可用；`giscus`在本地环境也确保能正常评论。摸了一天也没摸清楚生产环境转圈的原因，求解惑。

<img width="750" alt="图片" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/85431995/b5834c2b-96d1-4496-b88d-e4a8ce0a7bfb">

// waline
```
comments:
  service: waline
  # Waline
  # https://waline.js.org/
  waline:
    js: https://unpkg.com/@waline/client@v2/dist/waline.js
    css: https://unpkg.com/@waline/client@v2/dist/waline.css
    # Waline server address url, you should set this to your own link
    serverURL: http://comment.resetsix.cn # waline 地址
    # If false, comment count will only be displayed in post page, not in home page
    commentCount: true
    # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
    pageview: false
    emoji: 
      - https://gcore.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs
 ```

// giscus
```
# comments:
#   service: giscus
#   # giscus
#   # https://giscus.app/zh-CN
#   giscus:
#     data-repo: resetsix/blog_giscus_comments # [在此输入仓库]
#     data-repo-id: R_kgDOLwyXtw # [在此输入仓库 ID]
#     data-category: Announcements # [在此输入分类名]
#     data-category-id: DIC_kwDOLwyXt84Ce0Nw
#     data-mapping: pathname
#     data-strict: 0
#     data-reactions-enabled: 1
#     data-emit-metadata: 0
#     data-input-position: top # top, bottom
#     data-theme: preferred_color_scheme
#     data-lang: zh-CN
#     data-loading: lazy
#     crossorigin: anonymous
```

**Comment by resetsix** [comment]
// _config.yml
url: https://resetsix.cn

**Comment by gsh1209** [comment]
你的主题使用了1.27.0最新版本，但是配置文件没有更新。新版本主题已经更新到waline3，你所使用的旧版配置文件还是waline2。

**Comment by gsh1209** [comment]
看起来你使用了这个commit之前的配置文件 https://github.com/xaoxuu/hexo-theme-stellar/commit/bdef4a11ba567b1e80fe6baaec6a083c1d28188e

**Comment by resetsix** [comment]
> 看起来你使用了这个commit之前的配置文件 [bdef4a1](https://github.com/xaoxuu/hexo-theme-stellar/commit/bdef4a11ba567b1e80fe6baaec6a083c1d28188e)

太对了果然是这样，解决了感谢大佬。

我还有一个疑惑，单独访问评论的时候有上方的邮箱选项，但是在博客中却没有。我翻遍了文档和配置文件中也没找到是在哪里配置的。

<img width="862" alt="图片" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/85431995/9507efdd-de4c-43d9-88e2-06eb8d6e91d9">


<img width="776" alt="图片" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/85431995/53aba445-6831-4a43-ab57-73b2920e9def">

**Comment by gsh1209** [comment]
因为你已经登录了，你可以点头像旁边的❌退出之后刷新看看，或者用另外的浏览器访问一下

**Comment by resetsix** [comment]
> 因为你已经登录了，你可以点头像旁边的❌退出之后刷新看看，或者用另外的浏览器访问一下

抱歉再次打扰。我还有最后一个问题，代码托管到`Github`后，无论我将站点部署到`Vercel`还是 CF，都只能使用默认自带的域名才能显示评论框，而访问自定义域名还是 loading。

我初步以为是`_config.yml`中`url`值没有配置正确的原因，但始终通过访问自定义域名的时候就是一直转圈。
```
url: https://resetsix.cn
```
站点配置的自定义域名也是同上。DNS 解析应该也是正确的，不然网站应该都访问不了。

---

通过网络我发现访问默认域名的时候会请求 `waline.js`和 `waline.css`，但是自定义域名只有 `waline.js`的请求

**Comment by resetsix** [comment]
<img width="1348" alt="图片" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/85431995/d261c2d0-e815-44e0-b0b2-8c732f8c9ed7">

默认域名 (有评论)
```
https://041ea7bd.kudoshinichix.pages.dev/1970/01/01/hello-world/
```
自定义域名 (loading)
```
https://resetsix.cn/1970/01/01/hello-world/
```

**Comment by gsh1209** [comment]
你需要看一下waline的日志，在使用cn域名访问的时候出现了什么错误。另外可以发一下你的waline配置帮助判断。

**Comment by resetsix** [comment]
> 你需要看一下waline的日志，在使用cn域名访问的时候出现了什么错误。另外可以发一下你的waline配置帮助判断。

代码托管：Github
站点部署：Vercel或Cloudflare
问题描述：生产环境通过自定义域名访问时(cn域名)无法加载出waline组件，默认域名正常。本地启动访问也正常。
因为我没有其他的域名，所以无法测试其他域名的情况。

能加载出评论框的站点(默认域名)

https://blog-ruby-pi-11.vercel.app/hello-world/

一直loading转圈无法加载出评论框的站点(cn域名)

https://www.resetsix.cn

www替换成blog也行，但效果始终都是 loading。

评论服务（正常）
```
https://comment.resetsix.cn/
```

提示：开了代理，也尝试清除过浏览器缓存。Chrome、Firefox也都用过。
配置如下
```yml
comments:
  service: waline # beaudar, utterances, giscus, twikoo, waline, artalk
  comment_title: 快来参与讨论吧~
  # Waline
  # https://waline.js.org/
  waline:
    js: https://gcore.jsdelivr.net/npm/@waline/client@3.1.2/dist/waline.js
    css: https://gcore.jsdelivr.net/npm/@waline/client@3.1.2/dist/waline.css
    meta_css: https://gcore.jsdelivr.net/npm/@waline/client@3.1.2/dist/waline-meta.css
    serverURL: https://comment.resetsix.cn # 默认域名 https://blog-comments-indol.vercel.app #v
    commentCount: false
    pageview: false
    copyright: false
    lang: zh-CN
```

正常加载会请求如下接口
```
https://comment.resetsix.cn/api/comment
```
而访问自定义域名不会请求上面的接口（只有一个waline.js）。我在博客中手动请求也没出现拦截或跨域的问题（状态码 200）

**Comment by gsh1209** [comment]
vercel上是有日志的，可能叫runtime logs，我已经不在vercel上部署了，没办法操作，你可以找一下你的vercel上面waline的日志

**Comment by resetsix** [comment]
> runtime logs

<img width="1919" alt="图片" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/85431995/d696e948-d052-4940-907c-01dc8068dce4">
默认域名时的请求
<img width="1852" alt="图片" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/85431995/530c0387-931d-449c-bef0-ba6b9ae663fa">


自定义域名就是不请求 comment 接口，反而去请求一个什么 rum 文件没见过
```
https://resetsix.cn/cdn-cgi/rum
```

<img width="1880" alt="图片" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/85431995/5c6eb1b3-8580-4336-a9bc-4fff799273ee">

<img width="1268" alt="图片" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/85431995/2b81486f-eaa0-4efa-8e13-f12bbd671b0a">

为啥会报 405 呢我丢，服务器禁止了使用当前HTTP 方法的请求

**Comment by resetsix** [comment]
> comment.resetsix.cn似乎是解析到了cloudflare ip。
> 
> 这个问题我目前没有思路，建议你删除所有的waline服务、域名解析和绑定记录，严格按照waline的文档重新部署并绑定域名，不需要在不同平台做尝试，vercel能跑通就说明配置没有问题。

虽然cn域名我在国内买的，但我把dns解析迁移到cf上的。所以waline自定义域名服务也是在cf上做的解析，但无论comment我是否只通过cf做dns解析代理加上也都这样。可能就是域名解析放在cf上的锅吧。

十分感谢回复，辛苦了。

**Comment by flechazoyang-google** [comment]
<img width="1210" height="706" alt="Image" src="https://github.com/user-attachments/assets/c98646bf-1b10-430b-bebd-94cef363219c" />
请问一下
我也是遇到这个问题，评论一直在加载，然后我用一个简单的测试网页试了可以

<img width="2549" height="1313" alt="Image" src="https://github.com/user-attachments/assets/c35e179d-6630-4731-b1fd-a22a4fcb0f3f" />

```yaml
  # Waline
  # https://waline.js.org/
  waline:
    js: https://gcore.jsdelivr.net/npm/@waline/client@3.1/dist/waline.js
    css: https://gcore.jsdelivr.net/npm/@waline/client@3.1/dist/waline.css
    meta_css: https://gcore.jsdelivr.net/npm/@waline/client@3.1/dist/waline-meta.css
    # Waline server address url, you should set this to your own link
    serverURL: https://comment.flechazo.icu # 评论后端地址
    # If false, comment count will only be displayed in post page, not in home page
    commentCount: true
    # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
    pageview: false
```

<img width="1874" height="1080" alt="Image" src="https://github.com/user-attachments/assets/213ebe15-e9ad-43ab-9257-fe37de7d0c8d" />
这个域名也是可以访问的

**Comment by gsh1209** [comment]
从第一个图来看，前端已经读到了“2评论” 评论数量，评论内容加载不出来，说明前后端通信应该是成功了一部分的。你的 waline server 部署在什么环境上？还是建议去看下后端日志 && F12 看看 console 有没有报错。

还有一点就是可以尝试把 waline client 版本更新到最新 3.13.0，直接改 stellar 配置文件里的三个链接就可以。

**Comment by flechazoyang-google** [comment]
非常感谢回答！
部署环境在vercel上

这个错误一直解决不了`Error: [Ipv4ToRegion] db file not exists : /var/task/node_modules/ip2region/data/ip2region.db`
然后这个评论数据也能够写入数据库，就是评论列表加载不出来，问了ai给了下面这个方法也没有解决

<img width="1169" height="555" alt="Image" src="https://github.com/user-attachments/assets/279bd8a9-48d3-4766-9f2c-6de1d716349a" />

日志：
```txt
2026-05-11 04:19:36.940 [info] [32m[2026-05-11T04:19:36.939] [4] [INFO][39m - SQL: SELECT "id","email","url","display_name","type","avatar","2fa","label","github","weibo","twitter","facebook","qq","id" FROM "wl_users" WHERE ( "id" = E'1' ) AND ( "type" != E'banned' ), Time: 3ms
2026-05-11 04:19:36.942 [info] [36m[2026-05-11T04:19:36.942] [4] [DEBUG][39m - Post Comment Start!
2026-05-11 04:19:36.944 [info] [36m[2026-05-11T04:19:36.942] [4] [DEBUG][39m - Post Comment initial Data: {
  link: '',
  mail: '3134825482@qq.com',
  nick: '妄司逸',
  pid: undefined,
  rid: undefined,
  ua: 'Mozilla/5.0 (Windows NT 11.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0',
  url: '/2026/05/06/域名注册与博客关联域名操作指南/',
  comment: '你好',
  ip: '185.241.41.112',
  insertedAt: 2026-05-11T04:19:36.942Z,
  user_id: 1
}
2026-05-11 04:19:36.944 [info] [36m[2026-05-11T04:19:36.943] [4] [DEBUG][39m - Comment post hooks preSave done!
2026-05-11 04:19:36.994 [info] [32m[2026-05-11T04:19:36.993] [4] [INFO][39m - SQL: SELECT indexname,indexdef FROM pg_indexes WHERE tablename='wl_comment', Time: 49ms
2026-05-11 04:19:37.040 [info] [32m[2026-05-11T04:19:37.040] [4] [INFO][39m - SQL: SELECT column_name,is_nullable,data_type FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name='wl_comment', Time: 95ms
2026-05-11 04:19:37.052 [info] [32m[2026-05-11T04:19:37.051] [4] [INFO][39m - SQL: INSERT INTO "wl_comment" ("user_id","insertedat","url","comment","ua","ip","link","mail","nick","status") VALUES (1,E'2026-05-11 04:19:36',E'/2026/05/06/域名注册与博客关联域名操作指南/',E'你好',E'Mozilla/5.0 (Windows NT 11.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0',E'185.241.41.112',E'',E'3134825482@qq.com',E'妄司逸',E'approved') RETURNING id, Time: 10ms
2026-05-11 04:19:37.053 [info] [36m[2026-05-11T04:19:37.052] [4] [DEBUG][39m - Comment have been added to storage.
2026-05-11 04:19:37.054 [info] Error: [Ipv4ToRegion] db file not exists : /var/task/node_modules/ip2region/data/ip2region.db
    at new Ipv4ToRegion (/var/task/node_modules/ip2region/dist/lib/ipv4.js:25:19)
    at new IP2Region (/var/task/node_modules/ip2region/dist/lib/index.js:13:21)
    at /var/task/node_modules/@waline/vercel/src/extend/think.js:13:18
    at Object.ip2region (/var/task/node_modules/@waline/vercel/src/extend/think.js:89:19)
    at formatCmt (/var/task/node_modules/@waline/vercel/src/controller/comment.js:53:32)
    at module.exports.postAction (/var/task/node_modules/@waline/vercel/src/controller/comment.js:235:29)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at cors (/var/task/node_modules/@koa/cors/index.js:109:16)
    at /var/task/node_modules/@waline/vercel/src/middleware/version.js:5:3
    at /var/task/node_modules/@waline/vercel/src/middleware/prefix-warning.js:27:3
2026-05-11 04:19:37.057 [info] Notification mail send success: undefined
2026-05-11 04:19:37.058 [info] [36m[2026-05-11T04:19:37.057] [4] [DEBUG][39m - Comment notify done!
2026-05-11 04:19:37.058 [info] [36m[2026-05-11T04:19:37.057] [4] [DEBUG][39m - Comment post hooks postSave done!
2026-05-11 04:19:37.059 [info] Error: [Ipv4ToRegion] db file not exists : /var/task/node_modules/ip2region/data/ip2region.db
    at new Ipv4ToRegion (/var/task/node_modules/ip2region/dist/lib/ipv4.js:25:19)
    at new IP2Region (/var/task/node_modules/ip2region/dist/lib/index.js:13:21)
    at /var/task/node_modules/@waline/vercel/src/extend/think.js:13:18
    at Object.ip2region (/var/task/node_modules/@waline/vercel/src/extend/think.js:89:19)
    at formatCmt (/var/task/node_modules/@waline/vercel/src/controller/comment.js:53:32)
    at module.exports.postAction (/var/task/node_modules/@waline/vercel/src/controller/comment.js:266:13)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at cors (/var/task/node_modules/@koa/cors/index.js:109:16)
    at /var/task/node_modules/@waline/vercel/src/middleware/version.js:5:3
    at /var/task/node_modules/@waline/vercel/src/middleware/prefix-warning.js:27:3
```
版本也改了
```yaml
waline:
    js: https://gcore.jsdelivr.net/npm/@waline/client@3.13.0/dist/waline.js
    css: https://gcore.jsdelivr.net/npm/@waline/client@3.13.0/dist/waline.css
    meta_css: https://gcore.jsdelivr.net/npm/@waline/client@3.13.0/dist/waline-meta.css
    # Waline server address url, you should set this to your own link
    serverURL: https://blogcomments-omega.vercel.app/ # 评论后端地址
    # If false, comment count will only be displayed in post page, not in home page
    commentCount: true
    # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
    pageview: false
```
控制台：

<img width="1330" height="1309" alt="Image" src="https://github.com/user-attachments/assets/05b51152-b171-499a-ba4c-2306adaba827" />

**Comment by thun888** [comment]
这个应该不是stellar的问题，可能需要你手动[下载IP数据库](https://github.com/yourtion/node-ip2region/tree/master/data)，放置到项目文件夹内，并且设置一个环境变量指向它
```
IP2REGION_DB_V4=./path-to/ip2region.db
IP2REGION_DB_V6=./path-to/ipv6wry.db
```
或者设置`DISABLE_REGION`为`true`禁用IP归属地显示

**Comment by flechazoyang-google** [comment]
搞了半天还是没弄好，不行还是用giscus吧，还是感谢兄弟们的帮助，第一次发issue没想到这么快就有回复，感谢感谢

**Comment by gsh1209** [comment]
> 搞了半天还是没弄好，不行还是用giscus吧，还是感谢兄弟们的帮助，第一次发issue没想到这么快就有回复，感谢感谢

暂时不方便用电脑回复:)

F12看了你博客的评论加载问题

你发在最新文章里的：“测试”，“你好” 两条评论评论其实已经从后端拿到了，请求返回是ok的。基本能确定是 client 问题。

参考 waline 仓库的 issue820，可能是有什么别的插件和 waline 有冲突。我对前端不太了解，你可以彻底关闭其他插件看看会不会恢复。

周末刚好升级了下 waline，至少能确定当前的 stellar(mainline) 是可以兼容 3.13.0 的waline client 的，所以可能还是要重点排查下自己对主题的修改和其他插件的影响。


补充：
katex 禁了试试看？

**Comment by flechazoyang-google** [comment]
感觉有道理，有空去看一下，还有就是我改了一点stellar主题里面的文件，可能被我改坏了😭，看一下能不能改回去，不懂的文件还是慎重

**Comment by thun888** [comment]
> 感觉有道理，有空去看一下，还有就是我改了一点stellar主题里面的文件，可能被我改坏了😭，看一下能不能改回去，不懂的文件还是慎重

可以提供下最小复现仓库，我这边试了下没问题。😂

**Comment by flechazoyang-google** [comment]
终于找到问题了，问题出在了config.stellar.yml配置文件的katex插件部分。
```yaml
katex:

    enable: true # hexo-renderer-markdown-it-plus 默认开启 katex，此选项仅用于引入样式

    inject: |

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.23/dist/katex.min.css" crossorigin="anonymous">

      <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.23/dist/katex.min.js" crossorigin="anonymous"></script>

      <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.23/dist/contrib/auto-render.min.js" crossorigin="anonymous"></script>

      <script>

        document.addEventListener("DOMContentLoaded", function() {

          renderMathInElement(document.body, {

            delimiters: [

              {left: "$$", right: "$$", display: true},

              {left: "$", right: "$", display: false}

            ]

          });

        });

      </script>
```
改成原来配置文件里的
```yaml
katex:
    enable: #true # hexo-renderer-markdown-it-plus 默认开启 katex，此选项仅用于引入样式
    inject: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.23/dist/katex.min.css" integrity="sha384-//SZkxyB7axjCAopkAL1E1rve+ZSPKapD89Lo/lLhcsXR+zOYl5z6zJZEFXil+q0" crossorigin="anonymous">

```
然后就可以加载出来了，也不知道什么时候改的😭，不过终于改回来了，非常感谢大家的帮助。

**Comment by gsh1209** [comment]
果然是 katex，如需使用 katex，可以更换渲染器 https://github.com/xaoxuu/hexo-theme-stellar/issues/548

**Comment by flechazoyang-google** [comment]
> 果然是 katex，如需使用 katex，可以更换渲染器 https://github.com/xaoxuu/hexo-theme-stellar/issues/548

问题看的很准👍，目前还没写到很多公式，不着急😊

**Comment by xaoxuu** [comment]
已解决：问题源于配置文件停留在 waline2，而主题已升级 waline3（排查过程见评论）。升级到当前版本并按新版 _config.yml 配置即可。
