### ISSUE TITLE
【bug】 本地编译后 _post/blog/.md 无法实时编译更新 【与 hexo-related-popular-posts 有关】

### ISSUE THREAD

**Issue by hermitlsr** [xaoxuu/hexo-theme-stellar#53]
## 问题描述：
在 使用 `hexo clean && hexo g && hexo s` 命令进行本地编译发布后，再对 `_post/blog/` 中的文件进行修改编写，会报错，无法编译
只要对其中的 `blog /.md` 文件有所修改就必须重新使用 `hexo clean && hexo g && hexo s` 命令才可正确显示。
该问题在 1.5 版本前未出现，出错的版本是 1.6.1
正常来讲，hexo 中只要不改动 theme 的代码，post 内容是可以实时刷新的，但是这里报错和 相关文章推荐 有关，报错内容显示 文章路径不对，要清除缓存。
通过测试可以确定是 相关文章推荐 引起的报错，关掉该功能后可以正常修改，实时编译。
推测是相关文章插件的问题，或者是与主题配置有所冲突。
我目前的解决方法：
写博文时，关掉文章推荐功能，最终发布时再打开该功能。
即设置主题：
```
article:
  related_posts:
    enable: false
```

## 报错信息：
报错分两部分：
1.当对 `.md` 文件有修改时报错
2. 刷线本地网页 ` http://localhost:4000` 报错
1. 当对 `.md` 文件有修改时报错：
```
[22:04:30.511] [hexo-related-popular-posts] error:  Because the post's path has been changed, the link can not be created successfully. Please remove the cache with the following command.
$ hexo clean
```
![](https://i.bmp.ovh/imgs/2022/01/56a9ee021d796b58.png)
2.  刷线本地网页 ` http://localhost:4000` 报错：
```
Unhandled rejection TypeError: F:\myblog-doc\test\themes\stellar\layout\post.ejs:25
    23| </article>
    24| <%- partial('_partial/main/article/read_next') %>
 >> 25| <%- partial('_partial/main/article/related_posts') %>
    26| <%- partial('_partial/plugins/comments/layout') %>
    27|

F:\myblog-doc\test\themes\stellar\layout\_partial\main\article\related_posts.ejs:16
    14| }
    15| %>
 >> 16| <%- layoutDiv() %>
    17|

Cannot read property 'path' of undefined
    at Object.module.exports.getList (F:\myblog-doc\test\node_modules\hexo-related-popular-posts\lib\list-json.js:93:55)    at module.exports (F:\myblog-doc\test\node_modules\hexo-related-popular-posts\lib\helper-json.js:3:19)
    at Object.<anonymous> (F:\myblog-doc\test\node_modules\hexo-related-popular-posts\index.js:177:40)
    at layoutDiv (eval at compile (F:\myblog-doc\test\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:16:13)
    at eval (eval at compile (F:\myblog-doc\test\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:27:17)
    at returnedFn (F:\myblog-doc\test\node_modules\ejs\lib\ejs.js:653:17)
    at _View._compiledSync (F:\myblog-doc\test\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (F:\myblog-doc\test\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (F:\myblog-doc\test\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at compile (F:\myblog-doc\test\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:51:17)
    at returnedFn (F:\myblog-doc\test\node_modules\ejs\lib\ejs.js:653:17)
    at _View._compiled (F:\myblog-doc\test\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (F:\myblog-doc\test\node_modules\hexo\lib\theme\view.js:39:17)
    at F:\myblog-doc\test\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (F:\myblog-doc\test\node_modules\bluebird\js\release\util.js:16:23)
    at F:\myblog-doc\test\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\myblog-doc\test\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:465:10)
    at resume_ (internal/streams/readable.js:963:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
![](https://s3.bmp.ovh/imgs/2022/01/5c93e683e41b843c.png)

## 复现：
使用作者的源文件`xaoxuu.github.io` 和 最新主题代码可以重现该问题

**Comment by xaoxuu** [comment]
这是插件的问题不是主题的问题

**Comment by hermitlsr** [comment]
好吧，果然是插件的问题，看样子只能每次写的时候先把这个关掉了。
或者有没有替代的插件 我查到了一个 ：[
hexo-recommended-posts](https://github.com/huiwang/hexo-recommended-posts)，不确定是否能够替代原来的功能而不出现这种情况

**Comment by xaoxuu** [comment]
这个相关性比较低

**Comment by xaoxuu** [comment]
你可以先用用看，不错的话我以后也换掉（几年前用的是这个hexo-recommended-posts）
