### ISSUE TITLE
用wiki构建心得页面时报错

### ISSUE THREAD

**Issue by pyxz-x** [xaoxuu/hexo-theme-stellar#546]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot create property 'id' on string '<hr>
<h2 id="wiki-toolstitle-123"><a href="#wiki-toolstitle-123" class="headerlink" title="wiki: toolstitle: 123"></a>wiki: tools<br>title: 123</h2>'
    at getWikiObject (G:\xz_blog\themes\stellar\scripts\events\lib\doc_tree.js:36:14)
    at module.exports (G:\xz_blog\themes\stellar\scripts\events\lib\doc_tree.js:62:14)
    at Hexo.<anonymous> (G:\xz_blog\themes\stellar\scripts\events\index.js:10:28)
    at Hexo.emit (node:events:525:35)
    at Hexo._generate (G:\xz_blog\node_modules\hexo\dist\hexo\index.js:380:14)
    at G:\xz_blog\node_modules\hexo\dist\hexo\index.js:298:25
    at tryCatcher (G:\xz_blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\xz_blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (G:\xz_blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\xz_blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\xz_blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (G:\xz_blog\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (G:\xz_blog\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (G:\xz_blog\node_modules\bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (G:\xz_blog\node_modules\bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (G:\xz_blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\xz_blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (G:\xz_blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (G:\xz_blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (G:\xz_blog\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (G:\xz_blog\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)

**Comment by apchy2018** [comment]
老板解决了么，我也遇到了，不知道是哪里配置错了

**Comment by M3ng9e** [comment]
为什么啊为什么啊 ，我也是这样 按照文档

**Comment by xaoxuu** [comment]
这个不太好排查，可能是哪里的yml配置出错了，使属性识别成了字符串。建议下载一下 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 示例源码对比下看看
