### ISSUE TITLE
使用emoji标签报错

### ISSUE THREAD

**Issue by cayzlh** [xaoxuu/hexo-theme-stellar#99]
# 报错讯息如下

17
INFO  Start processing
[18](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:19)
FATAL {
[19](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:20)
  err: Template render error: (unknown path)
[20](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:21)
    ReferenceError: outputNoteBlock is not defined
[21](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:22)
      at Object._prettifyError (/home/runner/work/blog-framework/blog-framework/node_modules/nunjucks/src/lib.js:36:11)
[22](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:23)
      at /home/runner/work/blog-framework/blog-framework/node_modules/nunjucks/src/environment.js:563:19
[23](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:24)
      at Template.root [as rootRenderFunc] (eval at _compile (/home/runner/work/blog-framework/blog-framework/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:440:3)
[24](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:25)
      at Template.render (/home/runner/work/blog-framework/blog-framework/node_modules/nunjucks/src/environment.js:552:10)
[25](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:26)
      at Environment.renderString (/home/runner/work/blog-framework/blog-framework/node_modules/nunjucks/src/environment.js:380:17)
[26](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:27)
      at /home/runner/work/blog-framework/blog-framework/node_modules/hexo/lib/extend/tag.js:236:16
[27](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:28)
      at tryCatcher (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/util.js:16:23)
[28](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:29)
      at Function.Promise.fromNode.Promise.fromCallback (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/promise.js:209:30)
[29](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:30)
      at Tag.render (/home/runner/work/blog-framework/blog-framework/node_modules/hexo/lib/extend/tag.js:235:20)
[30](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:31)
      at Object.onRenderEnd (/home/runner/work/blog-framework/blog-framework/node_modules/hexo/lib/hexo/post.js:297:22)
[31](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:32)
      at /home/runner/work/blog-framework/blog-framework/node_modules/hexo/lib/hexo/render.js:79:21
[32](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:33)
      at tryCatcher (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/util.js:16:23)
[33](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:34)
      at Promise._settlePromiseFromHandler (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/promise.js:547:31)
[34](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:35)
      at Promise._settlePromise (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/promise.js:604:18)
[35](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:36)
      at Promise._settlePromise0 (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/promise.js:649:10)
[36](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:37)
      at Promise._settlePromises (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/promise.js:729:18)
[37](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:38)
      at _drainQueueStep (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/async.js:93:12)
[38](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:39)
      at _drainQueue (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/async.js:86:9)
[39](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:40)
      at Async._drainQueues (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/async.js:102:5)
[40](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:41)
      at Immediate.Async.drainQueues (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/async.js:15:14)
[41](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:42)
      at processImmediate (internal/timers.js:456:21) {
[42](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:43)
    cause: Template render error: (unknown path)
[43](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:44)
      ReferenceError: outputNoteBlock is not defined
[44](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:45)
        at Object._prettifyError (/home/runner/work/blog-framework/blog-framework/node_modules/nunjucks/src/lib.js:36:11)
[45](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:46)
        at /home/runner/work/blog-framework/blog-framework/node_modules/nunjucks/src/environment.js:563:19
[46](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:47)
        at Template.root [as rootRenderFunc] (eval at _compile (/home/runner/work/blog-framework/blog-framework/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:440:3)
[47](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:48)
        at Template.render (/home/runner/work/blog-framework/blog-framework/node_modules/nunjucks/src/environment.js:552:10)
[48](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:49)
        at Environment.renderString (/home/runner/work/blog-framework/blog-framework/node_modules/nunjucks/src/environment.js:380:17)
[49](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:50)
        at /home/runner/work/blog-framework/blog-framework/node_modules/hexo/lib/extend/tag.js:236:16
[50](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:51)
        at tryCatcher (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/util.js:16:23)
[51](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:52)
        at Function.Promise.fromNode.Promise.fromCallback (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/promise.js:209:30)
[52](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:53)
        at Tag.render (/home/runner/work/blog-framework/blog-framework/node_modules/hexo/lib/extend/tag.js:235:20)
[53](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:54)
        at Object.onRenderEnd (/home/runner/work/blog-framework/blog-framework/node_modules/hexo/lib/hexo/post.js:297:22)
[54](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:55)
        at /home/runner/work/blog-framework/blog-framework/node_modules/hexo/lib/hexo/render.js:79:21
[55](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:56)
        at tryCatcher (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/util.js:16:23)
[56](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:57)
        at Promise._settlePromiseFromHandler (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/promise.js:547:31)
[57](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:58)
        at Promise._settlePromise (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/promise.js:604:18)
[58](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:59)
        at Promise._settlePromise0 (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/promise.js:649:10)
[59](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:60)
        at Promise._settlePromises (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/promise.js:729:18)
[60](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:61)
        at _drainQueueStep (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/async.js:93:12)
[61](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:62)
        at _drainQueue (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/async.js:86:9)
[62](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:63)
        at Async._drainQueues (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/async.js:102:5)
[63](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:64)
        at Immediate.Async.drainQueues (/home/runner/work/blog-framework/blog-framework/node_modules/bluebird/js/release/async.js:15:14)
[64](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:65)
        at processImmediate (internal/timers.js:456:21),
[65](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:66)
    isOperational: true
[66](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:67)
  }
[67](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:68)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
[68](https://github.com/cayzlh/blog-framework/runs/6878183534?check_suite_focus=true#step:9:69)
Error: Process completed with exit code 2.

**Comment by xaoxuu** [comment]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/16400144/187072934-ac4d6f7e-91e1-48b3-9cec-b5bad57a184e.png">
应该是代码合并出问题了，你本地找一下这个东西把它删掉，看看主题源码里面对应的地方改成什么了
